`define SIGNED_ADD      6'd0
`define UNSIGNED_ADD    6'd1
`define SIGNED_SUB      6'd2
`define UNSIGNED_SUB    6'd3
`define SIGNED_MUL      6'd4
`define UNSIGNED_MUL    6'd5
`define SIGNED_DIV      6'd6
`define UNSIGNED_DIV    6'd7
`define AND             6'd8
`define OR              6'd9
`define XOR             6'd10
`define NOR             6'd11
`define SIGNED_SHIFTL   6'd12
`define SIGNED_SHIFTR   6'd13
`define UNSIGNED_SHIFTR 6'd14